//! Generated Element Definitions - DO NOT EDIT MANUALLY!
//!
//! Phase 1: Data-Driven Core
//! This file is auto-generated by scripts/generate-elements.js
//! Sources: definitions/elements.json, definitions/reactions.json
//!
//! To add a new element or reaction: edit JSON files and run 'npm run codegen'

use wasm_bindgen::prelude::*;

/// Element ID as u8 for compact storage
pub type ElementId = u8;

// ============================================================================
// ELEMENT CONSTANTS
// ============================================================================

pub const EL_EMPTY: ElementId = 0;
pub const EL_STONE: ElementId = 1;
pub const EL_SAND: ElementId = 2;
pub const EL_WOOD: ElementId = 3;
pub const EL_METAL: ElementId = 4;
pub const EL_ICE: ElementId = 5;
pub const EL_WATER: ElementId = 6;
pub const EL_OIL: ElementId = 7;
pub const EL_LAVA: ElementId = 8;
pub const EL_ACID: ElementId = 9;
pub const EL_STEAM: ElementId = 10;
pub const EL_SMOKE: ElementId = 11;
pub const EL_FIRE: ElementId = 12;
pub const EL_SPARK: ElementId = 13;
pub const EL_ELECTRICITY: ElementId = 14;
pub const EL_GUNPOWDER: ElementId = 15;
pub const EL_CLONE: ElementId = 16;
pub const EL_VOID: ElementId = 17;
pub const EL_DIRT: ElementId = 18;
pub const EL_SEED: ElementId = 19;
pub const EL_PLANT: ElementId = 20;
pub const ELEMENT_COUNT: usize = 21;

// ============================================================================
// CATEGORY CONSTANTS
// ============================================================================

pub type CategoryId = u8;
pub const CAT_SOLID: CategoryId = 0;
pub const CAT_POWDER: CategoryId = 1;
pub const CAT_LIQUID: CategoryId = 2;
pub const CAT_GAS: CategoryId = 3;
pub const CAT_ENERGY: CategoryId = 4;
pub const CAT_UTILITY: CategoryId = 5;
pub const CAT_BIO: CategoryId = 6;

// ============================================================================
// ELEMENT FLAGS (BitMask) - Phase 1 Data-Driven
// ============================================================================

pub type ElementFlags = u32;

pub const FLAG_NONE: ElementFlags = 0;
pub const FLAG_FLAMMABLE: ElementFlags = 1;
pub const FLAG_CONDUCTIVE: ElementFlags = 2;
pub const FLAG_LIQUID: ElementFlags = 4;
pub const FLAG_GAS: ElementFlags = 8;
pub const FLAG_POWDER: ElementFlags = 16;
pub const FLAG_SOLID: ElementFlags = 32;
pub const FLAG_ENERGY: ElementFlags = 64;
pub const FLAG_UTILITY: ElementFlags = 128;
pub const FLAG_BIO: ElementFlags = 256;
pub const FLAG_IGNORE_GRAVITY: ElementFlags = 512;
pub const FLAG_CORROSIVE: ElementFlags = 1024;
pub const FLAG_HOT: ElementFlags = 2048;
pub const FLAG_COLD: ElementFlags = 4096;
pub const FLAG_RIGID: ElementFlags = 8192;

// ============================================================================
// PHYSICS CONSTANTS - Phase 2 Newtonian Physics
// ============================================================================

pub const GRAVITY: f32 = 0.5;
pub const AIR_FRICTION: f32 = 0.98;
pub const MAX_VELOCITY: f32 = 10.0;

/// Check if element has flag (branchless)
#[inline(always)]
pub fn has_flag(flags: ElementFlags, flag: ElementFlags) -> bool {
    (flags & flag) != 0
}

// ============================================================================
// ELEMENT PROPERTIES
// ============================================================================

/// Element properties struct - Phase 2: includes physics (bounce, friction)
#[derive(Clone, Copy)]
pub struct ElementProps {
    pub color: u32,
    pub density: f32,
    pub category: CategoryId,
    pub flags: ElementFlags,
    pub dispersion: u8,
    pub lifetime: u16,
    pub default_temp: f32,
    pub heat_conductivity: u8,
    // Phase 2: Newtonian Physics
    pub bounce: f32,      // Collision bounce factor (0.0 = no bounce, 1.0 = full bounce)
    pub friction: f32,    // Velocity decay per frame (1.0 = no decay, 0.0 = instant stop)
}

impl ElementProps {
    #[inline(always)]
    pub fn flammable(&self) -> bool { has_flag(self.flags, FLAG_FLAMMABLE) }
    #[inline(always)]
    pub fn conductive(&self) -> bool { has_flag(self.flags, FLAG_CONDUCTIVE) }
    #[inline(always)]
    pub fn is_liquid(&self) -> bool { has_flag(self.flags, FLAG_LIQUID) }
    #[inline(always)]
    pub fn is_gas(&self) -> bool { has_flag(self.flags, FLAG_GAS) }
    #[inline(always)]
    pub fn is_solid(&self) -> bool { has_flag(self.flags, FLAG_SOLID) }
    #[inline(always)]
    pub fn is_powder(&self) -> bool { has_flag(self.flags, FLAG_POWDER) }
    #[inline(always)]
    pub fn ignores_gravity(&self) -> bool { has_flag(self.flags, FLAG_IGNORE_GRAVITY) }
}

/// Static element data - indexed by ElementId
pub static ELEMENT_DATA: [ElementProps; ELEMENT_COUNT] = [
    // 0: Empty
    ElementProps {
        color: 0xFF0A0A0A,
        density: 0.0,
        category: CAT_SOLID,
        flags: 32, // 0x0020
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 5,
        bounce: 0.0,
        friction: 0.0,
    },
    // 1: Stone
    ElementProps {
        color: 0xFF808080,
        density: 2500.0,
        category: CAT_SOLID,
        flags: 32, // 0x0020
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 10,
        bounce: 0.0,
        friction: 0.0,
    },
    // 2: Sand
    ElementProps {
        color: 0xFFC2B280,
        density: 1600.0,
        category: CAT_POWDER,
        flags: 16, // 0x0010
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 15,
        bounce: 0.2,
        friction: 0.9,
    },
    // 3: Wood
    ElementProps {
        color: 0xFF8B4513,
        density: 600.0,
        category: CAT_SOLID,
        flags: 33, // 0x0021
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 5,
        bounce: 0.0,
        friction: 0.0,
    },
    // 4: Metal
    ElementProps {
        color: 0xFFA9A9A9,
        density: 7800.0,
        category: CAT_SOLID,
        flags: 34, // 0x0022
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 90,
        bounce: 0.0,
        friction: 0.0,
    },
    // 5: Ice
    ElementProps {
        color: 0xFFA5F2F3,
        density: 916.0,
        category: CAT_SOLID,
        flags: 4128, // 0x1020
        dispersion: 0,
        lifetime: 0,
        default_temp: -10.0,
        heat_conductivity: 20,
        bounce: 0.0,
        friction: 0.0,
    },
    // 6: Water
    ElementProps {
        color: 0xFF4169E1,
        density: 1000.0,
        category: CAT_LIQUID,
        flags: 6, // 0x0006
        dispersion: 8,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 40,
        bounce: 0.0,
        friction: 0.95,
    },
    // 7: Oil
    ElementProps {
        color: 0xFF4A4A2A,
        density: 800.0,
        category: CAT_LIQUID,
        flags: 5, // 0x0005
        dispersion: 5,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 15,
        bounce: 0.0,
        friction: 0.95,
    },
    // 8: Lava
    ElementProps {
        color: 0xFFFF4500,
        density: 2500.0,
        category: CAT_LIQUID,
        flags: 2052, // 0x0804
        dispersion: 2,
        lifetime: 0,
        default_temp: 1000.0,
        heat_conductivity: 30,
        bounce: 0.0,
        friction: 0.95,
    },
    // 9: Acid
    ElementProps {
        color: 0xFF39FF14,
        density: 1050.0,
        category: CAT_LIQUID,
        flags: 1030, // 0x0406
        dispersion: 5,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 35,
        bounce: 0.0,
        friction: 0.95,
    },
    // 10: Steam
    ElementProps {
        color: 0xB4E0E0E0,
        density: 0.6,
        category: CAT_GAS,
        flags: 8, // 0x0008
        dispersion: 6,
        lifetime: 0,
        default_temp: 100.0,
        heat_conductivity: 10,
        bounce: 0.0,
        friction: 0.99,
    },
    // 11: Smoke
    ElementProps {
        color: 0xC83F3F3F,
        density: 1.1,
        category: CAT_GAS,
        flags: 8, // 0x0008
        dispersion: 4,
        lifetime: 0,
        default_temp: 50.0,
        heat_conductivity: 5,
        bounce: 0.0,
        friction: 0.99,
    },
    // 12: Fire
    ElementProps {
        color: 0xFFFF6600,
        density: 0.3,
        category: CAT_ENERGY,
        flags: 2112, // 0x0840
        dispersion: 0,
        lifetime: 60,
        default_temp: 800.0,
        heat_conductivity: 50,
        bounce: 0.0,
        friction: 1.0,
    },
    // 13: Spark
    ElementProps {
        color: 0xFFFFFF00,
        density: 0.1,
        category: CAT_ENERGY,
        flags: 64, // 0x0040
        dispersion: 0,
        lifetime: 10,
        default_temp: 500.0,
        heat_conductivity: 50,
        bounce: 0.0,
        friction: 1.0,
    },
    // 14: Electricity
    ElementProps {
        color: 0xFF00FFFF,
        density: 0.0,
        category: CAT_ENERGY,
        flags: 64, // 0x0040
        dispersion: 0,
        lifetime: 3,
        default_temp: 200.0,
        heat_conductivity: 80,
        bounce: 0.0,
        friction: 1.0,
    },
    // 15: Gunpowder
    ElementProps {
        color: 0xFF404040,
        density: 1400.0,
        category: CAT_POWDER,
        flags: 17, // 0x0011
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 10,
        bounce: 0.2,
        friction: 0.9,
    },
    // 16: Clone
    ElementProps {
        color: 0xFF00FF00,
        density: f32::INFINITY,
        category: CAT_UTILITY,
        flags: 640, // 0x0280
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 0,
        bounce: 0.0,
        friction: 1.0,
    },
    // 17: Void
    ElementProps {
        color: 0xFF000000,
        density: f32::INFINITY,
        category: CAT_UTILITY,
        flags: 640, // 0x0280
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 0,
        bounce: 0.0,
        friction: 1.0,
    },
    // 18: Dirt
    ElementProps {
        color: 0xFF5C4033,
        density: 1200.0,
        category: CAT_POWDER,
        flags: 16, // 0x0010
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 10,
        bounce: 0.2,
        friction: 0.9,
    },
    // 19: Seed
    ElementProps {
        color: 0xFFE2C489,
        density: 1100.0,
        category: CAT_BIO,
        flags: 257, // 0x0101
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 5,
        bounce: 0.1,
        friction: 0.85,
    },
    // 20: Plant
    ElementProps {
        color: 0xFF228B22,
        density: 900.0,
        category: CAT_BIO,
        flags: 257, // 0x0101
        dispersion: 0,
        lifetime: 0,
        default_temp: 20.0,
        heat_conductivity: 10,
        bounce: 0.1,
        friction: 0.85,
    },
];

// ============================================================================
// REACTION LOOKUP TABLE (LUT) - O(1) Access
// ============================================================================

/// Reaction result from LUT
#[derive(Clone, Copy, Debug)]
pub struct Reaction {
    /// What victim becomes (EL_EMPTY = destroyed)
    pub target_becomes: ElementId,
    /// What aggressor becomes (255 = unchanged, EL_EMPTY = destroyed)
    pub source_becomes: u8,
    /// Probability 0-255 (255 = 100%)
    pub chance: u8,
    /// Spawn byproduct (EL_EMPTY = none)
    pub spawn: ElementId,
}

impl Reaction {
    pub const NO_CHANGE: u8 = 255;
}

/// Reaction LUT size: 256 * 256 = 65536 entries
pub const REACTION_LUT_SIZE: usize = 65536;

/// Reaction LUT initialization data (sparse): (index, reaction)
pub static REACTION_INIT_DATA: [(usize, Reaction); 22] = [
    (1544, Reaction { target_becomes: 1, source_becomes: 10, chance: 38, spawn: 10 }), // water_lava
    (1548, Reaction { target_becomes: 0, source_becomes: 10, chance: 77, spawn: 0 }), // water_fire
    (2051, Reaction { target_becomes: 12, source_becomes: 255, chance: 77, spawn: 11 }), // lava_wood
    (2053, Reaction { target_becomes: 10, source_becomes: 1, chance: 77, spawn: 0 }), // lava_ice
    (2054, Reaction { target_becomes: 10, source_becomes: 1, chance: 38, spawn: 10 }), // lava_water
    (2055, Reaction { target_becomes: 12, source_becomes: 255, chance: 102, spawn: 11 }), // lava_oil
    (2063, Reaction { target_becomes: 12, source_becomes: 255, chance: 255, spawn: 11 }), // lava_gunpowder
    (2066, Reaction { target_becomes: 1, source_becomes: 255, chance: 13, spawn: 0 }), // lava_dirt
    (2068, Reaction { target_becomes: 12, source_becomes: 255, chance: 128, spawn: 11 }), // lava_plant
    (2305, Reaction { target_becomes: 0, source_becomes: 0, chance: 26, spawn: 11 }), // acid_stone
    (2307, Reaction { target_becomes: 0, source_becomes: 0, chance: 51, spawn: 0 }), // acid_wood
    (2308, Reaction { target_becomes: 0, source_becomes: 0, chance: 13, spawn: 0 }), // acid_metal
    (2309, Reaction { target_becomes: 6, source_becomes: 0, chance: 51, spawn: 0 }), // acid_ice
    (2322, Reaction { target_becomes: 0, source_becomes: 0, chance: 13, spawn: 0 }), // acid_dirt
    (2324, Reaction { target_becomes: 0, source_becomes: 0, chance: 38, spawn: 0 }), // acid_plant
    (3075, Reaction { target_becomes: 12, source_becomes: 11, chance: 26, spawn: 11 }), // fire_wood
    (3077, Reaction { target_becomes: 6, source_becomes: 0, chance: 77, spawn: 10 }), // fire_ice
    (3078, Reaction { target_becomes: 10, source_becomes: 0, chance: 128, spawn: 0 }), // fire_water
    (3079, Reaction { target_becomes: 12, source_becomes: 11, chance: 51, spawn: 11 }), // fire_oil
    (3087, Reaction { target_becomes: 12, source_becomes: 12, chance: 255, spawn: 11 }), // fire_gunpowder
    (3091, Reaction { target_becomes: 12, source_becomes: 11, chance: 51, spawn: 0 }), // fire_seed
    (3092, Reaction { target_becomes: 12, source_becomes: 11, chance: 26, spawn: 11 }), // fire_plant
];

/// Reaction System with O(1) lookup
pub struct ReactionSystem {
    lut: [Option<Reaction>; REACTION_LUT_SIZE],
}

impl ReactionSystem {
    /// Create new reaction system from init data
    pub fn new() -> Self {
        // Initialize with None
        let mut lut = [None; REACTION_LUT_SIZE];
        
        // Populate from generated data
        for (idx, reaction) in REACTION_INIT_DATA.iter() {
            lut[*idx] = Some(*reaction);
        }
        
        Self { lut }
    }
    
    /// O(1) reaction lookup - FAST!
    #[inline(always)]
    pub fn get(&self, aggressor: ElementId, victim: ElementId) -> Option<&Reaction> {
        let idx = ((aggressor as usize) << 8) | (victim as usize);
        // SAFETY: idx is always < 65536 since both IDs are u8
        #[cfg(not(debug_assertions))]
        unsafe { self.lut.get_unchecked(idx).as_ref() }
        #[cfg(debug_assertions)]
        self.lut[idx].as_ref()
    }
}

impl Default for ReactionSystem {
    fn default() -> Self {
        Self::new()
    }
}

/// Get element properties by ID
#[inline]
pub fn get_props(id: ElementId) -> &'static ElementProps {
    &ELEMENT_DATA[id as usize]
}

/// Get color with variation - EXACT TypeScript algorithm
/// Returns ABGR format for direct copy to Canvas ImageData
pub fn get_color_with_variation(id: ElementId, seed: u8) -> u32 {
    let base = ELEMENT_DATA[id as usize].color;
    let i = (seed & 31) as i32;
    let variation = (i - 16) * 2;
    
    let a = (base >> 24) & 0xFF;
    let r = (((base >> 16) & 0xFF) as i32 + variation).clamp(0, 255) as u32;
    let g = (((base >> 8) & 0xFF) as i32 + variation).clamp(0, 255) as u32;
    let b = ((base & 0xFF) as i32 + variation).clamp(0, 255) as u32;
    
    (a << 24) | (b << 16) | (g << 8) | r
}

// ============================================================================
// ELEMENT TYPE ENUM (for JS compatibility)
// ============================================================================

#[wasm_bindgen]
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ElementType {
    Empty = 0,
    Stone = 1,
    Sand = 2,
    Wood = 3,
    Metal = 4,
    Ice = 5,
    Water = 6,
    Oil = 7,
    Lava = 8,
    Acid = 9,
    Steam = 10,
    Smoke = 11,
    Fire = 12,
    Spark = 13,
    Electricity = 14,
    Gunpowder = 15,
    Clone = 16,
    Void = 17,
    Dirt = 18,
    Seed = 19,
    Plant = 20,
}

impl ElementType {
    pub fn to_id(self) -> ElementId {
        self as ElementId
    }
    
    pub fn props(self) -> &'static ElementProps {
        get_props(self as ElementId)
    }
}
