/**
 * Generated Element Definitions - DO NOT EDIT MANUALLY!
 *
 * This file is auto-generated by scripts/generate-elements.js
 * Source: definitions/elements.json
 *
 * To add a new element: edit definitions/elements.json and run 'npm run codegen'
 */

// ============================================================================
// ELEMENT ID CONSTANTS
// ============================================================================

export const EL_EMPTY = 0
export const EL_STONE = 1
export const EL_SAND = 2
export const EL_WOOD = 3
export const EL_METAL = 4
export const EL_ICE = 5
export const EL_WATER = 6
export const EL_OIL = 7
export const EL_LAVA = 8
export const EL_ACID = 9
export const EL_STEAM = 10
export const EL_SMOKE = 11
export const EL_FIRE = 12
export const EL_SPARK = 13
export const EL_ELECTRICITY = 14
export const EL_GUNPOWDER = 15
export const EL_CLONE = 16
export const EL_VOID = 17
export const EL_DIRT = 18
export const EL_SEED = 19
export const EL_PLANT = 20
export const ELEMENT_COUNT = 21

// ============================================================================
// CATEGORY CONSTANTS
// ============================================================================

export const CAT_SOLID = 0
export const CAT_POWDER = 1
export const CAT_LIQUID = 2
export const CAT_GAS = 3
export const CAT_ENERGY = 4
export const CAT_UTILITY = 5
export const CAT_BIO = 6

// ============================================================================
// UI CATEGORY DEFINITIONS
// ============================================================================

export interface UiCategoryDef {
  key: string
  label: string
  sort: number
}

export const UI_CATEGORIES: UiCategoryDef[] = [
  { key: "solids", label: "Solids", sort: 0 },
  { key: "liquids", label: "Liquids", sort: 1 },
  { key: "gases", label: "Gases", sort: 2 },
  { key: "energy", label: "Energy", sort: 3 },
  { key: "utility", label: "Utility", sort: 4 },
  { key: "bio", label: "Nature", sort: 5 },
]

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export type ElementId = number
export type CategoryId = number

export type ElementType = 'empty' | 'stone' | 'sand' | 'wood' | 'metal' | 'ice' | 'water' | 'oil' | 'lava' | 'acid' | 'steam' | 'smoke' | 'fire' | 'spark' | 'electricity' | 'gunpowder' | 'clone' | 'void' | 'dirt' | 'seed' | 'plant'

export type CategoryType = 'solid' | 'powder' | 'liquid' | 'gas' | 'energy' | 'utility' | 'bio'

// ============================================================================
// MAPPINGS
// ============================================================================

export const ELEMENT_NAME_TO_ID: Record<ElementType, ElementId> = {
  empty: EL_EMPTY,
  stone: EL_STONE,
  sand: EL_SAND,
  wood: EL_WOOD,
  metal: EL_METAL,
  ice: EL_ICE,
  water: EL_WATER,
  oil: EL_OIL,
  lava: EL_LAVA,
  acid: EL_ACID,
  steam: EL_STEAM,
  smoke: EL_SMOKE,
  fire: EL_FIRE,
  spark: EL_SPARK,
  electricity: EL_ELECTRICITY,
  gunpowder: EL_GUNPOWDER,
  clone: EL_CLONE,
  void: EL_VOID,
  dirt: EL_DIRT,
  seed: EL_SEED,
  plant: EL_PLANT,
}

export const ELEMENT_ID_TO_NAME: ElementType[] = [
  'empty',
  'stone',
  'sand',
  'wood',
  'metal',
  'ice',
  'water',
  'oil',
  'lava',
  'acid',
  'steam',
  'smoke',
  'fire',
  'spark',
  'electricity',
  'gunpowder',
  'clone',
  'void',
  'dirt',
  'seed',
  'plant',
]

export const CATEGORY_NAME_TO_ID: Record<CategoryType, CategoryId> = {
  solid: CAT_SOLID,
  powder: CAT_POWDER,
  liquid: CAT_LIQUID,
  gas: CAT_GAS,
  energy: CAT_ENERGY,
  utility: CAT_UTILITY,
  bio: CAT_BIO,
}

// ============================================================================
// ELEMENT PROPERTIES
// ============================================================================

// ============================================================================
// ELEMENT FLAGS - Phase 1 Data-Driven
// ============================================================================

export const FLAG_NONE = 0
export const FLAG_FLAMMABLE = 1
export const FLAG_CONDUCTIVE = 2
export const FLAG_LIQUID = 4
export const FLAG_GAS = 8
export const FLAG_POWDER = 16
export const FLAG_SOLID = 32
export const FLAG_ENERGY = 64
export const FLAG_UTILITY = 128
export const FLAG_BIO = 256
export const FLAG_IGNORE_GRAVITY = 512
export const FLAG_CORROSIVE = 1024
export const FLAG_HOT = 2048
export const FLAG_COLD = 4096
export const FLAG_RIGID = 8192

export type ElementFlags = number

export function hasFlag(flags: ElementFlags, flag: ElementFlags): boolean {
  return (flags & flag) !== 0
}

export interface ElementProps {
  id: ElementId
  name: ElementType
  category: CategoryId
  flags: ElementFlags
  color: number
  density: number
  dispersion: number
  lifetime: number
  defaultTemp: number
  heatConductivity: number
  hidden?: boolean
  ui?: { category: string; displayName: string; description: string; sort: number; hidden?: boolean }
}

export const ELEMENT_DATA: ElementProps[] = [
  {
    id: EL_EMPTY,
    name: 'empty',
    category: CAT_SOLID,
    flags: 32,
    color: 0xFF0A0A0A,
    density: 0,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 5, hidden: true,
    ui: { category: "utility", displayName: "Empty", description: "", sort: 0, hidden: true },
  },
  {
    id: EL_STONE,
    name: 'stone',
    category: CAT_SOLID,
    flags: 32,
    color: 0xFF808080,
    density: 2500,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 10,
    ui: { category: "solids", displayName: "Stone", description: "Heavy solid, melts at high temperature", sort: 0 },
  },
  {
    id: EL_SAND,
    name: 'sand',
    category: CAT_POWDER,
    flags: 16,
    color: 0xFFC2B280,
    density: 1600,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 15,
    ui: { category: "solids", displayName: "Sand", description: "Falls and piles up, melts into glass", sort: 1 },
  },
  {
    id: EL_WOOD,
    name: 'wood',
    category: CAT_SOLID,
    flags: 33,
    color: 0xFF8B4513,
    density: 600,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 5,
    ui: { category: "solids", displayName: "Wood", description: "Flammable solid", sort: 2 },
  },
  {
    id: EL_METAL,
    name: 'metal',
    category: CAT_SOLID,
    flags: 34,
    color: 0xFFA9A9A9,
    density: 7800,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 90,
    ui: { category: "solids", displayName: "Metal", description: "Conducts heat and electricity", sort: 3 },
  },
  {
    id: EL_ICE,
    name: 'ice',
    category: CAT_SOLID,
    flags: 4128,
    color: 0xFFA5F2F3,
    density: 916,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: -10,
    heatConductivity: 20,
    ui: { category: "solids", displayName: "Ice", description: "Melts from fire/lava, floats on water", sort: 4 },
  },
  {
    id: EL_WATER,
    name: 'water',
    category: CAT_LIQUID,
    flags: 6,
    color: 0xFF4169E1,
    density: 1000,
    dispersion: 4,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 40,
    ui: { category: "liquids", displayName: "Water", description: "Flows, evaporates, extinguishes fire", sort: 0 },
  },
  {
    id: EL_OIL,
    name: 'oil',
    category: CAT_LIQUID,
    flags: 5,
    color: 0xFF4A4A2A,
    density: 800,
    dispersion: 5,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 15,
    ui: { category: "liquids", displayName: "Oil", description: "Flammable liquid, floats on water", sort: 1 },
  },
  {
    id: EL_LAVA,
    name: 'lava',
    category: CAT_LIQUID,
    flags: 2052,
    color: 0xFFFF4500,
    density: 2500,
    dispersion: 2,
    lifetime: 0,
    defaultTemp: 1000,
    heatConductivity: 30,
    ui: { category: "liquids", displayName: "Lava", description: "Hot liquid, ignites flammables", sort: 2 },
  },
  {
    id: EL_ACID,
    name: 'acid',
    category: CAT_LIQUID,
    flags: 1030,
    color: 0xFF39FF14,
    density: 1050,
    dispersion: 5,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 35,
    ui: { category: "liquids", displayName: "Acid", description: "Dissolves stone, metal, wood (1:1)", sort: 3 },
  },
  {
    id: EL_STEAM,
    name: 'steam',
    category: CAT_GAS,
    flags: 8,
    color: 0xB4E0E0E0,
    density: 0.6,
    dispersion: 6,
    lifetime: 0,
    defaultTemp: 100,
    heatConductivity: 10,
    ui: { category: "gases", displayName: "Steam", description: "Rises up, condenses into water", sort: 0 },
  },
  {
    id: EL_SMOKE,
    name: 'smoke',
    category: CAT_GAS,
    flags: 8,
    color: 0xC82F2F2F,
    density: 1.1,
    dispersion: 4,
    lifetime: 0,
    defaultTemp: 50,
    heatConductivity: 5,
    ui: { category: "gases", displayName: "Smoke", description: "Rises and dissipates", sort: 1 },
  },
  {
    id: EL_FIRE,
    name: 'fire',
    category: CAT_ENERGY,
    flags: 2112,
    color: 0xFFFF6600,
    density: 0.3,
    dispersion: 0,
    lifetime: 60,
    defaultTemp: 800,
    heatConductivity: 50,
    ui: { category: "energy", displayName: "Fire", description: "Burns flammables, extinguished by water", sort: 0 },
  },
  {
    id: EL_SPARK,
    name: 'spark',
    category: CAT_ENERGY,
    flags: 64,
    color: 0xFFFFFF00,
    density: 0.1,
    dispersion: 0,
    lifetime: 10,
    defaultTemp: 500,
    heatConductivity: 50,
    ui: { category: "energy", displayName: "Spark", description: "Brief ignition source", sort: 1 },
  },
  {
    id: EL_ELECTRICITY,
    name: 'electricity',
    category: CAT_ENERGY,
    flags: 64,
    color: 0xFF00FFFF,
    density: 0,
    dispersion: 0,
    lifetime: 3,
    defaultTemp: 200,
    heatConductivity: 80,
    ui: { category: "energy", displayName: "Electric", description: "Flows through conductors", sort: 2 },
  },
  {
    id: EL_GUNPOWDER,
    name: 'gunpowder',
    category: CAT_POWDER,
    flags: 17,
    color: 0xFF404040,
    density: 1400,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 10,
    ui: { category: "solids", displayName: "Gunpowder", description: "Explosive! Ignites instantly from fire", sort: 5 },
  },
  {
    id: EL_CLONE,
    name: 'clone',
    category: CAT_UTILITY,
    flags: 640,
    color: 0xFF00FF00,
    density: Infinity,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 0,
    ui: { category: "utility", displayName: "Clone", description: "Duplicates touching particles", sort: 0 },
  },
  {
    id: EL_VOID,
    name: 'void',
    category: CAT_UTILITY,
    flags: 640,
    color: 0xFF000000,
    density: Infinity,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 0,
    ui: { category: "utility", displayName: "Void", description: "Destroys all particles", sort: 1 },
  },
  {
    id: EL_DIRT,
    name: 'dirt',
    category: CAT_POWDER,
    flags: 16,
    color: 0xFF5C4033,
    density: 1200,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 10,
    ui: { category: "bio", displayName: "Dirt", description: "Fertile soil for plants", sort: 0 },
  },
  {
    id: EL_SEED,
    name: 'seed',
    category: CAT_BIO,
    flags: 257,
    color: 0xFFE2C489,
    density: 1100,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 5,
    ui: { category: "bio", displayName: "Seed", description: "Plant on wet dirt to grow!", sort: 1 },
  },
  {
    id: EL_PLANT,
    name: 'plant',
    category: CAT_BIO,
    flags: 257,
    color: 0xFF228B22,
    density: 900,
    dispersion: 0,
    lifetime: 0,
    defaultTemp: 20,
    heatConductivity: 10,
    ui: { category: "bio", displayName: "Plant", description: "Grows with water, burns easily", sort: 2 },
  },
]

// ============================================================================
// REACTIONS - Phase 1 Data-Driven
// ============================================================================

export interface Reaction {
  aggressor: ElementType
  victim: ElementType
  resultAggressor: ElementType | null
  resultVictim: ElementType | null
  chance: number
  spawn: ElementType | null
}

export const REACTIONS: Reaction[] = [
  { aggressor: 'fire', victim: 'wood', resultAggressor: 'smoke', resultVictim: 'fire', chance: 0.1, spawn: 'smoke' },
  { aggressor: 'fire', victim: 'oil', resultAggressor: 'smoke', resultVictim: 'fire', chance: 0.2, spawn: 'smoke' },
  { aggressor: 'fire', victim: 'water', resultAggressor: 'empty', resultVictim: 'steam', chance: 0.5, spawn: null },
  { aggressor: 'fire', victim: 'ice', resultAggressor: 'empty', resultVictim: 'water', chance: 0.3, spawn: 'steam' },
  { aggressor: 'fire', victim: 'gunpowder', resultAggressor: 'fire', resultVictim: 'fire', chance: 1, spawn: 'smoke' },
  { aggressor: 'fire', victim: 'plant', resultAggressor: 'smoke', resultVictim: 'fire', chance: 0.1, spawn: 'smoke' },
  { aggressor: 'fire', victim: 'seed', resultAggressor: 'smoke', resultVictim: 'fire', chance: 0.2, spawn: null },
  { aggressor: 'lava', victim: 'water', resultAggressor: 'stone', resultVictim: 'steam', chance: 0.15, spawn: 'steam' },
  { aggressor: 'lava', victim: 'wood', resultAggressor: null, resultVictim: 'fire', chance: 0.3, spawn: 'smoke' },
  { aggressor: 'lava', victim: 'oil', resultAggressor: null, resultVictim: 'fire', chance: 0.4, spawn: 'smoke' },
  { aggressor: 'lava', victim: 'ice', resultAggressor: 'stone', resultVictim: 'steam', chance: 0.3, spawn: null },
  { aggressor: 'lava', victim: 'gunpowder', resultAggressor: null, resultVictim: 'fire', chance: 1, spawn: 'smoke' },
  { aggressor: 'lava', victim: 'plant', resultAggressor: null, resultVictim: 'fire', chance: 0.5, spawn: 'smoke' },
  { aggressor: 'lava', victim: 'dirt', resultAggressor: null, resultVictim: 'stone', chance: 0.05, spawn: null },
  { aggressor: 'acid', victim: 'stone', resultAggressor: 'empty', resultVictim: 'empty', chance: 0.1, spawn: 'smoke' },
  { aggressor: 'acid', victim: 'metal', resultAggressor: 'empty', resultVictim: 'empty', chance: 0.05, spawn: null },
  { aggressor: 'acid', victim: 'wood', resultAggressor: 'empty', resultVictim: 'empty', chance: 0.2, spawn: null },
  { aggressor: 'acid', victim: 'ice', resultAggressor: 'empty', resultVictim: 'water', chance: 0.2, spawn: null },
  { aggressor: 'acid', victim: 'plant', resultAggressor: 'empty', resultVictim: 'empty', chance: 0.15, spawn: null },
  { aggressor: 'acid', victim: 'dirt', resultAggressor: 'empty', resultVictim: 'empty', chance: 0.05, spawn: null },
  { aggressor: 'water', victim: 'lava', resultAggressor: 'steam', resultVictim: 'stone', chance: 0.15, spawn: 'steam' },
  { aggressor: 'water', victim: 'fire', resultAggressor: 'steam', resultVictim: 'empty', chance: 0.3, spawn: null },
]

// ============================================================================
// UI HELPERS
// ============================================================================

/** Get elements visible in the UI palette (excludes 'empty') */
export const VISIBLE_ELEMENTS = ELEMENT_DATA.filter(e => !e.hidden)

/** Get elements by category for UI grouping */
export function getElementsByCategory(category: CategoryType): ElementProps[] {
  const catId = CATEGORY_NAME_TO_ID[category]
  return ELEMENT_DATA.filter(e => e.category === catId && !e.hidden)
}
